## https://www.youtube.com/watch?v=5rtGBwBuzQE
version: '3'

services:
    ## https://haugene.github.io/docker-transmission-openvpn/
 transmission-openvpn:
    image: haugene/transmission-openvpn:${TRANSMISSION_VERSION:-4.0}
    container_name: pvr_transmission
    volumes:
        - ${DOWNLOADS_PATH}:/data/downloads
        - ${PVR_PATH}/transmission:/data/transmission-home
        - /etc/localtime:/etc/localtime:ro
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - CREATE_TUN_DEVICE=true
        - OPENVPN_CONFIG=
        - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
        - OPENVPN_CONFIG=${OPENVPN_CONFIG}
        - OPENVPN_USERNAME=${OPENVPN_USERNAME}
        - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
        - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --dhcp-option DNS 9.9.9.9
        - WEBPROXY_ENABLED=false
        - LOCAL_NETWORK=${TRANSMISSION_LOCAL_NETWORK}
        - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
        - TRANSMISSION_HOME=/data/transmission-home
        - TRANSMISSION_DOWNLOAD_DIR=/data/downloads
        - TRANSMISSION_INCOMPLETE_DIR=/data/downloads/#incomplete
        - TRANSMISSION_WATCH_DIR=/data/downloads/#watch
        - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
        - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
        - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
        - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=4
        - TRANSMISSION_WEB_UI=transmission-web-control
        - TRANSMISSION_ALT_SPEED_DOWN=1000
        - TRANSMISSION_ALT_SPEED_ENABLED=true
        - TRANSMISSION_ALT_SPEED_TIME_BEGIN=300
        - TRANSMISSION_ALT_SPEED_TIME_DAY=127
        - TRANSMISSION_ALT_SPEED_TIME_ENABLED=true
        - TRANSMISSION_ALT_SPEED_TIME_END=1380
        - TRANSMISSION_ALT_SPEED_UP=2
        - TRANSMISSION_PEER_PORT=47444
        - DNS=9.9.9.9,149.112.112.112
    cap_add:
        - NET_ADMIN
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091
        # - 9117:9117
        # - 7878:7878
        # - 8989:8989
        # - 8686:8686
        # - 5299:5299
    restart: unless-stopped
 
#  jackett:
#     image: linuxserver/jackett
#     container_name: jackett
#     network_mode: "service:transmission-openvpn"
#     environment:
#         - PUID=1000
#         - PGID=100
#         - TZ=America/New_York
#         - AUTO_UPDATE=true #optional
#         - RUN_OPTS=#optional
#     volumes:
#         - /srv/dev-disk-by-label-data/appdata/jackett:/config
#         #Jackett only needs config
#     restart: unless-stopped
 
#  radarr:
#     image: linuxserver/radarr
#     network_mode: "service:transmission-openvpn"
#     container_name: radarr
#     environment:
#         - PUID=1000
#         - PGID=100
#         - TZ=America/New_York
#         - UMASK_SET=022 #optional
#     volumes:
#         - /srv/dev-disk-by-label-data/appdata/radarr:/config
#         - /srv/dev-disk-by-label-data/media:/media
#     restart: unless-stopped
 
#  sonarr:
#     image: linuxserver/sonarr
#     network_mode: "service:transmission-openvpn"
#     container_name: sonarr
#     environment:
#         - PUID=1000
#         - PGID=100
#         - TZ=America/New_York
#         - UMASK_SET=022 #optional
#     volumes:
#         - /srv/dev-disk-by-label-data/appdata/sonarr:/config
#         - /srv/dev-disk-by-label-data/media/:/media
#     restart: unless-stopped
 
#  lidarr:
#     image: linuxserver/lidarr
#     network_mode: "service:transmission-openvpn"
#     container_name: lidarr
#     environment:
#         - PUID=1000
#         - PGID=100
#         - TZ=America/New_York
#         - UMASK_SET=022 #optional
#     volumes:
#         - /srv/dev-disk-by-label-data/appdata/lidarr:/config
#         - /srv/dev-disk-by-label-data/media/:/media
#     restart: unless-stopped
 
#  lazylibrarian:
#     image: linuxserver/lazylibrarian
#     network_mode: "service:transmission-openvpn"
#     container_name: lazylibrarian
#     environment:
#         - PUID=1000
#         - PGID=100
#          - TZ=America/New_York
#         #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
#     volumes:
#         - /srv/dev-disk-by-label-data/appdata/lazylibrarian:/config
#         - /srv/dev-disk-by-label-data/media/:/media
#     restart: unless-stopped