## # PLEX MEDIA SERVER
##
## Plex personal media server magically scans and organizes your files, sorting 
## your media intuitively and beautifully.
## https://github.com/plexinc/pms-docker
---
networks:
  default:
    name: plex_network
    driver: bridge
  transmission_network:
    external: true

services:
  plex:
    container_name: plex_media_server
    image: plexinc/pms-docker:${PMS_VERSION:-latest}
    restart: unless-stopped
    networks:
      - default
      - transmission_network
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
      - ADVERTISE_IP=http://${PLEX_IP_ADDRESS}:32400/
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - ${PLEX_PATH}:/config
      - ${PLEX_TRANSCODE}:/transcode
      - ${MEDIA_MOUNTS}:/data