## # PLEX MEDIA SERVER
##
## Plex personal media server magically scans and organizes your files, sorting 
## your media intuitively and beautifully.
## https://github.com/plexinc/pms-docker
---
# networks:
#   default:
#     name: plex_network
#     driver: bridge
#   transmission_network:
#     external: true

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host # Container's networking appears to be the host
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
      # - ADVERTISE_IP=${PLEX_IP_ADDRESS}
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
    volumes:
      - ${PLEX_PATH}:/config
      # - ${MOVIES_PATH}:/movies
      # - ${TV_PATH}:/tv
      - ${MEDIA_MOUNTS}:/data
      - /dev/shm:/transcode # Mount RAM for transcoding
    devices:
      - /dev/dri:/dev/dri # GPU for hardware transcoding
    restart: unless-stopped